version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    labels:
      - "name=redis"
      - "mode=standalone"
    command: redis-server
    #    volumes:
    #      - ./redis/data:/data
    #      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Seoul
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  mongo-db:
    image: mongo:5.0
    container_name: mongo-db
    volumes:
      - ./mongodb:/docker-entrypoint-initdb.d:ro
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: shop
networks:
  web-network:
    driver: bridge
