version: "3.1"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    labels:
      - "name=redis"
      - "mode=standalone"
    command: redis-server
    networks:
      - web-network
    #    volumes:
    #      - ./redis/data:/data
    #      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
networks:
  web-network:
    driver: bridge
